repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      # file
      - id: end-of-file-fixer
        description: Fixes missing end-of-file newline in files.
      - id: mixed-line-ending
        args: ["--fix=lf"]
        description: Forces to replace line ending by the UNIX 'lf' character.
      - id: trailing-whitespace
        description: Trims trailing whitespace.
      - id: check-added-large-files
        args: ["--maxkb=200"]
        description: Checks for large files being added to git.
      # format
      - id: check-yaml
      - id: check-toml
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-docstring-first
      - id: debug-statements
      - id: check-builtin-literals
      - id: detect-private-key

  - repo: https://github.com/pycqa/bandit
    rev: 1.8.6
    hooks:
      - id: bandit

  - repo: https://github.com/rbubley/mirrors-prettier
    rev: "v3.7.3"
    hooks:
      - id: prettier
        types_or: [yaml, markdown, toml, json]

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.21.2
    hooks:
      - id: pyupgrade
        args: ["--py312-plus"]
        files: "^backend/.*\\.py$"

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.7
    hooks:
      - id: ruff
        args:
          - --fix
        files: "^backend/.*\\.py$"
      - id: ruff-format
        files: "^backend/.*\\.py$"

  - repo: https://github.com/pycqa/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
        name: flake8
        types: [python]
        args:
          - --max-line-length=120
          - --ignore=B008,W503
        additional_dependencies:
          - flake8-bugbear
          - flake8-print
          - flake8-docstrings
        exclude: "__init__.py"
        files: "^backend/.*\\.py$"
